require: rubocop-rails

AllCops:
  NewCops: enable

inherit_from:
  - https://raw.githubusercontent.com/ausaccessfed/aaf-gumboot/develop/aaf-rubocop.yml

Rails/BulkChangeTable:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
