default: &default
  adapter: mysql2
  username: validator_app
  password: password
  host: 127.0.0.1
  pool: 5
  encoding: utf8
  collation: utf8_bin

development:
  <<: *default
  database: validator_development

test:
  <<: *default
  database: validator_test

production:
  <<: *default
  username: <%= ENV['EXAMPLE_DB_USERNAME'] %>
  password: <%= ENV['EXAMPLE_DB_PASSWORD'] %>
  database: <%= ENV['EXAMPLE_DB_NAME'] %>
